version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - PROXY_URI=${PROXY_URI}
      - APP_NAME=${APP_NAME}
      - PG_URI=${PG_URI}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/usr/src/app/src  # Match WORKDIR from Dockerfile

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      # These should match values from PG_URI in .env file
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
